### ISSUE TITLE
FINOS Configuration of Glue Microsite

### ISSUE THREAD

**Issue by mcleo-d** [finos/glue#104]
## FINOS Configuration of Glue Microsite

This issue is to request the FINOS team configures the Glue repository to build and deploy the Glue Docusaurus microsite as found in https://github.com/finos/glue/tree/master/website

- [x] Configure `netlify` on the Glue repo for microsite preview and deployment upon pull requests raised and merged.
- [x] Delete branch `gh-pages` - https://github.com/finos/glue/issues/104#issuecomment-880636179
- [x] Delete Docusaurus Build Action - #107
- [x] Delete Docusaurus Build Action badge in `README.md` - #108
- [x] Creation of CNAME record that reflects https://glue.finos.org

Many thanks,

James 🚀

**Comment by bkrumov** [comment]
Hey, @mcleo-d and @maoo, 
I've just included the CNAME file with the domain that is going to be available in the future.
Do you have any other requests for us?

**Comment by mcleo-d** [comment]
Hey @bkrumov,

Thanks for adding these changes ...
- https://github.com/finos/glue/commit/3e83b450d230eb3449138949fa096ad09a676bb9#r53476054
- https://github.com/finos/glue/commit/3e83b450d230eb3449138949fa096ad09a676bb9#r53476043

I believe this is good and will work with @maoo on `netlify` configuration and go live.

Cheers ...

James 🚀

**Comment by maoo** [comment]
Website deployed on https://finosglue.netlify.app/

Every change on master will be reflected on this URL; as soon as this is reviewed, I can easily update this name to glue.finos.org.

Please note that:
1. From now on, every PR submitted against `master` will build a preview website and post the URL into the GitHub PR
2. The Docusaurus build action is not needed anymore, you can safely delete https://github.com/finos/glue/blob/master/.github/workflows/docusaurus.yml and related badge in the README.md
3. the `gh-pages` branch can be safely deleted, as Netlify doesn't use it

Re. mobile version, I had a quick look at it and it is readable, as it's a quite common way for our community to consume contents. Feel free to review it too on your end.

Please let me know if you have any questions, and when you're comfortable updating the name to `glue.finos.org`.

TY

**Comment by mcleo-d** [comment]
> Re. mobile version, I had a quick look at it and it is readable, as it's a quite common way for our community to consume contents. Feel free to review it too on your end.

I suggest the Glue maintainers review this with relevant product owners and prioritise as appropriate against Glue product features for a future release.  I hope this works?

**Comment by mcleo-d** [comment]
> Website deployed on https://finosglue.netlify.app/
🚀🚀🚀

**Comment by cm-howard** [comment]
Great to see this online - thanks to everyone involved! :+1: :blue_heart:

**Comment by maoo** [comment]
> Great to see this online - thanks to everyone involved! 👍 💙

Agreed! One note, let's not share this URL outside EPAM and FINOS, until we complete the deployment and point to glue.finos.org . TY!

**Comment by mcleo-d** [comment]
Hey @maoo 

I believe the Glue team are good with the creation of `glue.finos.org`. I suggest moving forward and any changes that need to be made to the site can be done through pull request if needed.

James.

**Comment by AnaAntonova** [comment]
Hey @maoo and @mcleo-d, I am ok to publish to glue.finos.org in case we can still make changes on the site. I just noticed some strange behavior on finosglue.netlify.app which will need to be fixed. I will send you some screenshots separately.

Best,
Ana

**Comment by maoo** [comment]
http://glue.finos.org is live! SSL certificates are being provisioned now, https should be ready shortly.

**Comment by mcleo-d** [comment]
`gh-pages` branch deleted by @mcleo-d as highlighted below and requested in this issue ...

![Screenshot 2021-07-15 at 12 58 48](https://user-images.githubusercontent.com/6029572/125784523-fb652283-001c-4705-a840-4b68a0a4c3d4.png)

**Comment by mcleo-d** [comment]
Hi @AnaAntonova 

Feel free to close this issue once all the tasks above have been completed by merging various related pull requests 😸  - https://github.com/finos/glue/issues/104#issue-944357046

James.

**Comment by AnaAntonova** [comment]
Hi @maoo @mcleo-d,

last week we've merged a fix which addresses some strange some unordered lists not being displayed on the landing page (https://github.com/finos/glue/pull/109). However, I am not sure this is deployed automatically to the glue.finos.org. Can you please check if this needs to be done manually?

Best,
Ana

**Comment by maoo** [comment]
Hi @AnaAntonova 

This is what I see on Netlify

<img width="715" alt="Screenshot 2021-07-20 at 11 17 44" src="https://user-images.githubusercontent.com/327285/126296009-21a846f7-7011-4e9a-b4b9-dbc842704d8f.png">

I suggest you always making changes via PRs, so you'll be able to see a preview of your changes.

HTH

**Comment by bkrumov** [comment]
Hi @maoo 

The changes were made via PR ([#109](https://github.com/finos/glue/pull/109)). You can see the [preview page](https://deploy-preview-109--finosglue.netlify.app/?utm_source=github&utm_campaign=bot_dp) contains the changes made prior to this fix for the landing page:
![image](https://user-images.githubusercontent.com/85564150/126297006-af2da25d-4c15-4b78-8ae3-684629239c66.png)

Borislav.

**Comment by bkrumov** [comment]
Hey @maoo,

I've checked the Netlify deploys and seems that the production one is failing with "Canceled build due to no content change". The preview deploy on the other hand is published successfully. 

![image](https://user-images.githubusercontent.com/85564150/126306378-31bbbca3-ff6c-432e-a53f-919c5bd42469.png)

Borislav.

**Comment by maoo** [comment]
That's interesting... here's what I see

<img width="1208" alt="Screenshot 2021-07-20 at 16 02 00" src="https://user-images.githubusercontent.com/327285/126337553-30076289-e5fe-461b-a737-38b091362943.png">

Question: where is Example.js supposed to be visualized? It seems that the file is not rendered out anywhere? At least, [google cant find it](https://www.google.com/search?q=site%3Aglue.finos.org+%22A+tool+for+the+Chief+Investment+Office%22&pws=0&gl=us&gws_rd=cr)

If the page is not linked, then it doesn't get added to the `build` folder, therefore Netlify doesn't find any change and skips the build.

**Comment by bkrumov** [comment]
Hey @maoo, 

The Example.js component is part of the landing page(home page) and represents the following content:
![image](https://user-images.githubusercontent.com/85564150/126339683-6fac2fa4-2b45-495a-b014-2964deac8d68.png)

The snippet above is from the [preview page](https://deploy-preview-109--finosglue.netlify.app/?utm_source=github&utm_campaign=bot_dp).

**Comment by bkrumov** [comment]
Hey @maoo,

I have a suggestion that may fix this issue that we have. What I think is happening is that the new build file with the latest changes is "almost" the same as the one that is cached by Netlify. It is possible Netlify's change detection engine to skip a build operation prior to improving the performance. Can you try to create a build hook in Netlify so we can manually trigger the build step and see if the latest changes will be published on production?

Regards,
Borislav
